name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

################################################################################
# setup                                                                        #
################################################################################

    - name: setup-runner
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential git zlib1g-dev libboost-all-dev libssl-dev

    - name: setup-runner-docker
      uses: docker/setup-buildx-action@v3

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

################################################################################
# build                                                                        #
################################################################################

    - name: build
      run: cmake -S . -B $BUILD_DIR && make -C $BUILD_DIR

################################################################################
# test                                                                         #
################################################################################

    - name: run-edit-client-terminal-tests
      run: $BUILD_DIR/edit-client-terminal/edit-client-terminal-tests

    - name: run-edit-common-tests
      run: $BUILD_DIR/edit-common/edit-common-tests
